listen_port: 54321
database: postgres
## Only one source for now
sources:
  - host: 127.0.0.1
    port: 5432
    ## TODO: Not fully implimented
    mode: hybrid # could be master or slave
    username: postgres
    password: postgres
